spring:
    application:
        name: enablerv1sampleapp
    cloud:
        client:
            hostname: ${environment.hostname}
            ipAddress: ${environment.ipAddress}
    output:
        ansi:
            enabled: always

logging:
    level:
        ROOT: INFO
        org.springframework: INFO
        com.ca.mfaas: DEBUG

##############################################################################################
# MFAAS configuration section
##############################################################################################
mfaas:
    discovery:
        serviceId: ${environment.serviceId}
        locations: ${environment.discoveryLocations}
        enabled: ${environment.discoveryEnabled:true}
        info:
            serviceTitle: ${environment.serviceTitle}
            description:  ${environment.serviceDescription}
            swaggerLocation: # populate this value with a json file from the resources folder to load a static swagger definition
        fetchRegistry: false
        region: default
    service:
        hostname: ${environment.hostname}
        ipAddress: ${environment.ipAddress}
    catalog-ui-tile:
        id: cademoapps
        title: Sample API Mediation Layer Applications
        description: Applications which demonstrate how to make a service integrated to the API Mediation Layer ecosystem
        version:  1.0.0
    server:
        port: ${environment.port}
        contextPath: /${spring.application.name}
        scheme: http

eureka:
    instance:
        appName: ${mfaas.discovery.serviceId}
        hostname: ${mfaas.service.hostname}
        statusPageUrl: ${mfaas.server.scheme}://${mfaas.service.hostname}:${mfaas.server.port}/${mfaas.server.contextPath}/application/info
        healthCheckUrl: ${mfaas.server.scheme}://${mfaas.service.hostname}:${mfaas.server.port}/${mfaas.server.contextPath}/application/health
        homePageUrl:
        metadata-map:
            routed-services:
                api_v1:
                    gateway-url: "api/v1"
                    service-url: ${mfaas.server.contextPath}/api/v1
                api-doc: # Intentionally using old format to retrieve Api-doc for testing purposes
                    gateway-url: "api/v1/api-doc"
                    service-url: ${mfaas.server.contextPath}/api-doc
            mfaas:
                api-info:
                    swagger:
                        location: ${mfaas.discovery.info.swaggerLocation:}
                    apiVersionProperties:
                        v1:
                            title: Service Integration Enabler V1 Sample App (spring boot 1.x)
                            description: Sample micro-service showing how to enable a Spring Boot v1.x application
                            version: 1.0.0
                            basePackage: com.ca.mfaas.sample.enable.v1.controller

                discovery:
                    catalogUiTile:
                        id: ${mfaas.catalog-ui-tile.id}
                        title:  ${mfaas.catalog-ui-tile.title}
                        description: ${mfaas.catalog-ui-tile.description}
                        version: ${mfaas.catalog-ui-tile.version}
                    enableApiDoc: ${mfaas.discovery.info.enableApiDoc:true}
                    service:
                        title: ${mfaas.discovery.info.serviceTitle}
                        description: ${mfaas.discovery.info.description}
    client:
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: ${mfaas.discovery.locations}
        fetchRegistry:  ${mfaas.discovery.fetchRegistry}
        region: ${mfaas.discovery.region}
        enabled: ${mfaas.discovery.enabled}

##############################################################################################
management:
    context-path: /application

server:
    address: ${mfaas.service.hostname}
    port: ${mfaas.server.port}
    context-path: ${mfaas.server.contextPath}

